version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=ecommerce
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  
  e-commerce:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce
    depends_on:
      - mongo
    ports:
      - 8080:8080

volumes:
  mongo-data: